# -*- coding: utf-8 -*-
"""Meu Primeiro Algoritmo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LOloX90zqaXbW-hsq5ztac63RetQnwAX
"""

num1 = input('Digite o primeiro número: ')
num2 = input('Digite o segundo número: ')

num1_convert = int(num1)
num2_convert = int(num2)

if num1_convert > num2_convert:
  print((num1_convert + num2_convert)/10)
elif num1_convert < num2_convert:
  print((num1_convert - num2_convert)*25)
else:
  print((num1_convert * num2_convert)/2)